### ISSUE TITLE
Define Acceptance Criteria for 1st Iteration

### ISSUE THREAD

**Issue by nlsdfnbch** [raiden-network/raiden-installer#1]
Define acceptance criteria for the raiden installer, including expectations for various scenarios.

**Comment by nlsdfnbch** [comment]
Some criteria I came up with:

 - The installer downloads the raiden binary's latest version from the github releases page.
 - The installer allows using an infura node to connect to the test network.
 - The installer allows using a locally installed Geth client to connect to the test network.
 - The installer allows using a locally installed Parity client to connect to the test network.
 - The installer allows using an existing Testnet account for connecting to the test network.
 - The installer offers creating an account for connecting to the test network.
 - The installer requests test net ether using a pre-defined faucet.
 - The installer requests test net tokens using a pre-defined faucet.
 - The installer creates a symlink to the raiden binary at /usr/local/bin/raiden by default.
 - The installer creates a desktop icon linking to the raiden binary by default.
 - The installer allows skipping the symlink creation.
 - The installer allows skipping the desktop icon creation.
 - If the installer failed or was interrupted at any step, it picks up at the beginning of the failed step on next execution.

**Comment by nlsdfnbch** [comment]
@christianbrb

**Comment by christianbrb** [comment]
@nlsdfnbch copied and added acceptance criteria
- The installer downloads the raiden binary's latest version from the github releases page.
- The installer allows the user to select a test network, where the Raiden contracts are deployed (Rinkeby, Kovan, Ropsten, Görli?)
- The installer allows using an infura node to connect to the test network.
- The installer is checking the Infura project id
- The installer allows using a locally or remotely installed Geth client to connect to the test network.
- The installer checks the connection to the installed Geth client
- The installer checks, if the installed Geth client is synched
- The installer allows using a locally or remotely installed Parity client to connect to the test network.
- The installer checks the connection to the installed Parity client
- The installer checks, if the installed Parity client is synched
- The installer allows using an existing Testnet account for connecting to the test network.
- The installer offers creating an account for connecting to the test network.
- The installer requests test net ether using a pre-defined faucet.
- The installer pre-selects a token, where tokens can be provided via a faucet
- The installer requests test net tokens using a pre-defined faucet.
- The installer creates a symlink to the raiden binary at /usr/local/bin/raiden by default.
- The installer creates a desktop icon linking to the raiden binary by default.
- The installer allows skipping the symlink creation.
- The installer allows skipping the desktop icon creation.
- The installer asks if the user wants to start Raiden
- If the installer failed or was interrupted at any step, it picks up at the beginning of the failed step on next execution.
