### ISSUE TITLE
A crash with `ValueError: Channel is not in an open state`

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-installer#31]
After running  the installer and performing some operations (sorry, I don't remember them precisely), the UI started reporting connection issues with localhost:5000, and I saw on the console

```
  File "raiden/connection_manager.py", line 322, in _join_partner
  File "raiden/api/python.py", line 610, in set_total_channel_deposit
ValueError: Channel is not in an open state.
```

I reported this crash also on the client repo https://github.com/raiden-network/raiden/issues/4451

**Comment by jomuel** [comment]
Closing this as the underlying problem in the client (raiden-network/raiden#4451) has been fixed.
