### ISSUE TITLE
Generated Raiden config file contains invalid setting

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden-installer#35]
The generated Raiden config file contains the invalid setting `keystore-file-path`.

The following message is printed by Raiden during start: `Unknown setting 'keystore-file-path' found in config file - ignoring.`

**Comment by lullis** [comment]
It is intentional. The installer needs to have an easy way to find out which keystore file corresponds to the account being used.

**Comment by palango** [comment]
Couldn't you make this a comment then?
