### ISSUE TITLE
Support arbitrary eth node rpc endpoints

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden-installer#39]
Have the option to use Infura is nice to get started quickly, but nfortunately Infura isn't safe to use with Raiden currently. 

It would be good if a user could enter their own eth node rpc url.

**Comment by christianbrb** [comment]
We want to keep the wizard right now as simple as possible and it is just planned to release it for the Görli testnet.

**Comment by lullis** [comment]
It actually is possible, the wording on the form does not indicate, but we accept either the infura id or a fully-formed URL for those that have their own eth node.
