### ISSUE TITLE
Pragmatic Programmer Documentation For The Raiden Wizard

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/raiden-installer#42]
**Objectives**
Write documentation for the Raiden Wizard that supports non-technical users and pragmatic developers who are curious about Raiden but not necessarily invested enough to go in-depth. This will provide more people with an opportunity to try out and interact with Raiden.

The end goal is to have documentation where the information is condensed and presented in an easily understandable way that does not come of as overwhelming. The documentation should also explicitly explain concepts that might not be familiar to many users, e.g. _what is a token network?_

This first iteration will cover the Raiden Wizard and all steps up to the Raiden Web UI.

**Next Steps**
- [x] Make a draft mapping out all key steps
- [x] Find how to structure the work in GitBook
- [x] Make GIF outlining steps to get an Infura Project ID
- [x] Make GIF of Raiden Wizard installation procedure
- [x] Share for feedback

**Comment by jomuel** [comment]
Is this done, @taleldayekh ? Can we close the issue?

**Comment by taleldayekh** [comment]
@jomuel Yes, I would say it is done. The Wizard docs will have to be updated though for the mainnet one when we have a functioning Wizard again but that would be a separate issue. I'll close this one now.
