### ISSUE TITLE
Installer Readme

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/raiden-installer#45]
The new installer readme looks nice and is very helpful for the first time user.

I would add three things:
- [x] Add a developer section
- [x] Adding a header near "Quick Start", that the user knows, that the readme is about the Raiden Wizard
- [x] Being more specific at https://github.com/raiden-network/raiden-installer#stop-raiden-from-running

**Comment by taleldayekh** [comment]
What do you suggest to be put in the developer section? The thing I can think of is the link to the API documentation but do we need an entire section for just that or do you have something else in mind?

**Comment by christianbrb** [comment]
Would be mored geared towards a contributor (see https://help.github.com/en/articles/setting-guidelines-for-repository-contributors). Creating a contributing.md and link to it at the end of the readme would do the job.

**Comment by taleldayekh** [comment]
A developer section has been added at the bottom with a link to the newly added CONTRIBUTING.md. I will close this issue now.
