### ISSUE TITLE
UX/UI feature requests

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/raiden-installer#56]
This issue consists of UX/UI feedback received from people testing the installer. I guess it's a thin line here between the Wizard and the WebUI.

### An End-To-End User Journey On-Boarding

The installer sets up Raiden in such a way that payments/transfers can be made as a very first thing when the installation is finished.

__Proposal__
* The user runs the Wizard, installs and sets up Raiden
* A token network is automatically joined, tokens are added and test channels are opened
* The landing screen would in this scenario not be the WebUI home screen but rather a screen where the user chooses a recipient and the amount of tokens to transfer

__Purpose__
Reduce the number of clicks and remove the procedure involved before the user can actually make any payments/transfers.

### Informative Setup Process

Provide the user with short information about the what and why of each setup step.

__Proposal__
E.g. "info screens"
![onboarding](https://st4.depositphotos.com/4177785/20849/v/1600/depositphotos_208491828-stock-illustration-relationships-development-onboarding-mobile-app.jpg)
* Screen describing why the account is funded with ETH (to open and close channels on-chain)
* Screen describing why the account is funded with ERC20 tokens (about the ERC20 standard and that tokens are deposited into channels and spent)
* Screen informing that the user can start Raiden again after a reboot

__Purpose__
A progress indicator for the setup process which also educates the user about key concepts

**Comment by lullis** [comment]
With the redesign brought for the mainnet release, perhaps we can close this?

**Comment by jomuel** [comment]
> With the redesign brought for the mainnet release, perhaps we can close this?

What do you think @taleldayekh ?

**Comment by taleldayekh** [comment]
@jomuel Agree, this one is not relevant anymore.
