### ISSUE TITLE
installer wasn't able to pop my browser

### ISSUE THREAD

**Issue by BOR4** [raiden-network/raiden-installer#58]
Guide says browser will open by itself. It didn't for me.
However when I opened myself and went to http://localhost:8888 it asked me for infura project id and I could proceed.

**Comment by BOR4** [comment]
this was mozilla (,y default broswer) ubuntu

**Comment by jomuel** [comment]
Could not reproduce with Firefox and Ubuntu. As a fallback for such situations we added a "wizard is ready" log message with the localhost URL so the user can open the page manually. (See issue #36)
