### ISSUE TITLE
Fund wallet should display both "Transfer via Web3 browser" and "Convert ETH into RDN" on the first run

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/raiden-installer#71]
Currently if the ETH balance is 0 the user sees only the "Transfer via Web3 browser"-button. When the user presses the button some ETH gets transferred and the user is taken back to the very same screen again that now displays an additional "Convert ETH into RDN"-button.

Display both buttons from the very start and make the second button disabled if the user has no ETH for the RDN's. This makes it a bit cleaner and also more obvious why I need the ETH.

It also removes the feeling of an additional screen/step when it in fact is the very same.

**Comment by lullis** [comment]
Resolved by PR #76
