### ISSUE TITLE
Invalid reply from pathfinding service

### ISSUE THREAD

**Issue by mat7ias** [raiden-network/raiden-installer#72]
## Problem Definition

The current installer on Goerli will use https://pfs-goerli-with-fee.services-dev.raiden.network instead of https://pfs-goerli-with-fee.services-test.raiden.network. I offered a temporary fix for someone running into this issue [on Reddit](https://www.reddit.com/r/raidennetwork/comments/drgudb/raiden_wizard_error/f6icjq2).

**Comment by taleldayekh** [comment]
The new Mac binary is uploaded and since it has the same filename no links need to be changed in the docs etc. When you're done with the Linux one @lullis close this issue.

**Comment by lullis** [comment]
The release is now updated with both new binaries and can be downloaded
